# Generated by Django 3.2.4 on 2021-09-18 10:20

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortby', models.IntegerField(choices=[(1, 'id'), (2, 'Title'), (3, 'ProjectUrl'), (4, 'created_at')], default=2, verbose_name='Sorting By')),
                ('sortkind', models.IntegerField(choices=[(1, 'id'), (2, 'Title'), (3, 'ProjectUrl'), (4, 'created_at')], default=1, verbose_name='Sorting Kind')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=150)),
                ('Thumbnail', models.ImageField(upload_to=app.models.thumbnail_dir_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
