# Generated by Django 3.2.4 on 2021-09-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalsoring',
            name='sortkind',
            field=models.IntegerField(choices=[(1, 'Asending'), (2, 'Desending')], default=1, verbose_name='Sorting Kind'),
        ),
    ]
