# Generated by Django 3.2.4 on 2021-09-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_portalsoring_sortkind'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ProjectUrl',
            field=models.CharField(default='-', max_length=250),
            preserve_default=False,
        ),
    ]
